// Top car brands and models sold in Spain
// Source: DGT matriculaciones + market data
export const vehicleDatabase: Record<string, string[]> = {
  "Alfa Romeo": ["Giulia", "Stelvio", "Tonale", "Giulietta", "MiTo"],
  "Audi": ["A1", "A3", "A4", "A5", "A6", "Q2", "Q3", "Q5", "Q7", "Q8", "TT", "e-tron"],
  "BMW": ["Serie 1", "Serie 2", "Serie 3", "Serie 4", "Serie 5", "X1", "X2", "X3", "X5", "Z4", "iX", "i4"],
  "Citroën": ["C1", "C3", "C3 Aircross", "C4", "C5 Aircross", "Berlingo", "C-Elysée", "SpaceTourer"],
  "Cupra": ["Born", "Formentor", "Leon", "Ateca", "Tavascan", "Terramar"],
  "Dacia": ["Sandero", "Duster", "Jogger", "Spring", "Logan"],
  "DS": ["DS 3", "DS 4", "DS 7", "DS 9"],
  "Fiat": ["500", "500X", "Panda", "Tipo", "Punto", "Doblò", "Ducato"],
  "Ford": ["Fiesta", "Focus", "Kuga", "Puma", "Mondeo", "EcoSport", "Transit", "Ranger", "Mustang", "Explorer"],
  "Honda": ["Civic", "CR-V", "HR-V", "Jazz", "ZR-V", "e:Ny1"],
  "Hyundai": ["i10", "i20", "i30", "Tucson", "Kona", "Bayon", "Santa Fe", "IONIQ 5", "IONIQ 6"],
  "Jeep": ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler", "Avenger"],
  "Kia": ["Picanto", "Rio", "Ceed", "Sportage", "Niro", "Stonic", "XCeed", "EV6", "EV9", "Sorento"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Range Rover", "Range Rover Sport", "Range Rover Evoque", "Range Rover Velar"],
  "Lexus": ["CT", "IS", "NX", "RX", "UX", "ES", "LC"],
  "Mazda": ["Mazda2", "Mazda3", "CX-3", "CX-5", "CX-30", "CX-60", "MX-5", "MX-30"],
  "Mercedes-Benz": ["Clase A", "Clase B", "Clase C", "Clase E", "Clase S", "CLA", "GLA", "GLB", "GLC", "GLE", "GLS", "EQA", "EQB", "EQC", "Sprinter", "Vito"],
  "Mini": ["Mini 3 puertas", "Mini 5 puertas", "Countryman", "Clubman", "Cabrio"],
  "Mitsubishi": ["ASX", "Eclipse Cross", "Outlander", "Space Star", "L200"],
  "Nissan": ["Micra", "Juke", "Qashqai", "X-Trail", "Leaf", "Ariya", "Navara", "Townstar"],
  "Opel": ["Corsa", "Astra", "Crossland", "Grandland", "Mokka", "Combo", "Vivaro", "Movano"],
  "Peugeot": ["208", "308", "2008", "3008", "5008", "508", "Rifter", "Partner", "Expert", "Boxer"],
  "Renault": ["Clio", "Captur", "Mégane", "Scénic", "Kadjar", "Arkana", "Kangoo", "Trafic", "Master", "ZOE", "Twingo", "Austral"],
  "Seat": ["Ibiza", "León", "Arona", "Ateca", "Tarraco", "Alhambra", "Mii"],
  "Škoda": ["Fabia", "Octavia", "Superb", "Kamiq", "Karoq", "Kodiaq", "Scala", "Enyaq"],
  "Smart": ["Fortwo", "Forfour", "#1", "#3"],
  "SsangYong": ["Tivoli", "Korando", "Rexton", "Torres"],
  "Subaru": ["Impreza", "XV", "Forester", "Outback", "Solterra"],
  "Suzuki": ["Swift", "Vitara", "S-Cross", "Ignis", "Jimny", "Across"],
  "Tesla": ["Model 3", "Model Y", "Model S", "Model X"],
  "Toyota": ["Yaris", "Yaris Cross", "Corolla", "C-HR", "RAV4", "Camry", "Land Cruiser", "Hilux", "Proace", "Aygo X", "bZ4X", "GR86", "Supra"],
  "Volkswagen": ["Polo", "Golf", "T-Cross", "T-Roc", "Tiguan", "Touareg", "Passat", "Arteon", "ID.3", "ID.4", "ID.5", "Caddy", "Transporter", "Crafter", "Up!"],
  "Volvo": ["XC40", "XC60", "XC90", "S60", "S90", "V60", "V90", "C40", "EX30", "EX90"],
  // Comerciales / Industriales
  "Iveco": ["Daily", "Eurocargo", "S-Way"],
  "MAN": ["TGE", "TGL", "TGM", "TGS", "TGX"],
  "Isuzu": ["D-Max", "N-Series"],
  "Maxus": ["eDeliver 3", "eDeliver 9", "T60", "T90"],
  "Piaggio": ["Porter", "Ape"],
};
