// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Post = Collections['posts']['schema']['_output']
export declare const posts: Post[]

export type Feature = Collections['features']['schema']['_output']
export declare const features: Feature[]

export type City = Collections['cities']['schema']['_output']
export declare const cities: City[]

export type Comparison = Collections['comparisons']['schema']['_output']
export declare const comparisons: Comparison[]
