// This file is generated by Velite

export { default as posts } from './posts.json' with { type: 'json' }
export { default as features } from './features.json' with { type: 'json' }
export { default as cities } from './cities.json' with { type: 'json' }
export { default as comparisons } from './comparisons.json' with { type: 'json' }